netflixuax/authentication/urls.py
from django.urls import path
from .views import user_register, user_login, user_logout

app_name = "authentication"

urlpatterns = [
    path("register/", user_register, name="register"),
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
]

netflixuax/netflixuax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("streaming.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("authentication.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

netflixuax/streaming/urls.py
from django.urls import path
from .views import home
from .views import movie_details
from .views import series_list, series_details
from .views import movies_list
from .views import my_list, add_to_list_m, add_to_list_s, remove_from_list

app_name = "streaming"


urlpatterns = [
    path("", home, name="home"),
    path("series/", series_list, name="series-list"),
    path("series/<int:series_id>/", series_details, name="series-details-page"),
    path("movies/", movies_list, name="movies-list"),
    path("movie/<int:movie_id>/", movie_details, name="movie-details-page"),
    path("my-list/", my_list, name="my-list"),
    path("my-list/add/movie/<int:movie_id>/", add_to_list_m, name="add-to-list"),
    path("my-list/add/series/<int:series_id>/", add_to_list_s, name="add-to-list"),
    path("my-list/remove/<int:movie_id>/", remove_from_list, name="remove-from-list"),
]

netflixuax/netflixuax/templates/netflixuax/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Lumflix
      {% endblock %}
    </title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <!-- Swiper CSS -->
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
  </head>
  <body>
    <!-- Barra de navegación -->
    <header class="header navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand logo" href="{% url 'streaming:home' %}">Lumflix</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="{% url 'streaming:home' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'series-list' %}active{% endif %}" href="{% url 'streaming:series-list' %}">Series</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'movies-list' %}active{% endif %}" href="{% url 'streaming:movies-list' %}">Películas</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'my-list' %}active{% endif %}" href="{% url 'streaming:my-list' %}">Mi lista</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'logout' %}active{% endif %}" href="{% url 'authentication:logout' %}">Cerrar Sesión</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'login' %}active{% endif %}" href="{% url 'authentication:login' %}">Iniciar Sesión</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'register' %}active{% endif %}" href="{% url 'authentication:register' %}">Registrarse</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </header>

    <!-- Contenido específico de cada página -->
    <main>
      {% block content %}

      {% endblock %}
    </main>

    <!-- Pie de página -->
    <footer class="footer bg-dark text-white text-center py-3">
      <div class="container">
        <p>© 2024 Lumflix. Todos los derechos reservados.</p>
        <ul class="list-inline">
          <li class="list-inline-item">
            <a href="#" class="text-white text-decoration-none">Términos de uso</a>
          </li>
          <li class="list-inline-item">
            <a href="#" class="text-white text-decoration-none">Política de privacidad</a>
          </li>
          <li class="list-inline-item">
            <a href="#" class="text-white text-decoration-none">Ayuda</a>
          </li>
        </ul>
      </div>
    </footer>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Swiper JS -->
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <!-- Swiper Initialization -->
    <script>
      document.addEventListener('DOMContentLoaded', () => {
        new Swiper('.mySwiper', {
          slidesPerView: 5,
          spaceBetween: 10,
          navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev'
          },
          loop: true
        })
      })
    </script>
  </body>
</html>